In [1]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
import librosa
import csv
import os
from glob import glob

In [161]:
import os

# Absolute path of a file
old_name = r"D:\COVID_COUGH_SOUNDS\1second_chunks_458\balanced_1s_not_aug\1s_balancedChunks\train\ff\1603942345102x_0.wav"
new_name = r"D:\COVID_COUGH_SOUNDS\1second_chunks_458\balanced_1s_not_aug\1s_balancedChunks\train\ff\1603942345102_0.wav"

# Renaming the file
os.rename(old_name, new_name)

In [180]:
root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/test/ss/'
#root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/train'
renam_filenames= []
for path, subdirs, files in os.walk(root):
    for name in files:
        #print(os.path.join(path, name))
        renam_filenames.append(os.path.join(path, name))

In [181]:
len(renam_filenames)

61

In [186]:
new_names =  []
for i in range(len(renam_filenames)):
    a = renam_filenames[i].split('/')[-1]
    s = a[:13] + "b" + a[13:]
    new_names.append(s)
    #print(s)

In [183]:
path = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/test/ss/'
new_filenames= []

for name in new_names:
        #print(os.path.join(path, name))
        new_filenames.append(os.path.join(path, name))

In [184]:
for i in range(len(renam_filenames)):
    os.rename(renam_filenames[i], new_filenames[i])

In [185]:
len(new_filenames)

61

In [171]:
a = renam_filenames[1].split('/')[-1]
s = a[:13] + "b" + a[13:]
print(a, s)

1603942345102_1.wav 1603942345102b_1.wav


In [ ]:
s = a[:13] + "b" + a[13:]

In [187]:
new_names =  []
for i in range(len(renam_filenames)):
    a = renam_filenames[i].split('/')[-1]
    s = a[:13] + "b" + a[13:]
    new_names.append(s)
    #print(s)

In [201]:
root = 'D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/train/'
#root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/train'
train_filenames= []
for path, subdirs, files in os.walk(root):
    for name in files:
        #print(os.path.join(path, name))
        train_filenames.append(os.path.join(path, name))

In [202]:
#DATA_DIR='D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP+COUGHVID_CHUNKS_50_OVERLAP/allergies/'
#filenames =glob(DATA_DIR + '/*.wav')

In [203]:
root_t = 'D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/test/'
#root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/train'
test_filenames= []
for path, subdirs, files in os.walk(root_t):
    for name in files:
        #print(os.path.join(path, name))
        test_filenames.append(os.path.join(path, name))

In [204]:
test_filenames[-104]

'D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/test/pneumonia\\1603942345102_speed_27.wav'

In [205]:
def load_audio_file(file_path):
    input_length = 16000
    data = librosa.core.load(file_path)[0] #, sr=16000
    return data

In [206]:
def get_data_files():
    # we will be leaving some files out, on purpose. Do not change this function!
    return [os.path.join(DATA_DIR, x) for x in sorted(os.listdir(DATA_DIR)) ]

In [207]:
def get_sound_id_from_file_path(file_path):
    a = file_path.split('\\')[-2:]
    #b= file_path.split('/')[-1:]
    #c= file_path.split('\\')[-1:]
    return a
    #return a, b

In [208]:
print(test_filenames[1])
correlation, key = get_sound_id_from_file_path(test_filenames[1])
correlation, key = get_sound_id_from_file_path(test_filenames[1])
d = correlation.split('/')[-1]
print(correlation)
print(key)
print(d)

D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/test/allergies\1598869457003_1.wav
D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/test/allergies
1598869457003_1.wav
allergies


In [198]:
len(train_filenames)

2010

In [199]:
correlation

'D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/test/allergies'

In [214]:
def extractWavFeatures(soundFilesFolder, csvFileName, xfilenames):
    print("The features of the files in the folder "+soundFilesFolder+" will be saved to "+csvFileName)
    header = 'key correlation chroma_stft rmse spectral_centroid spectral_bandwidth rolloff zero_crossing_rate'
    for i in range(1, 21):
        header += f' mfcc{i}'
    #header += ' label'
    header = header.split()
    print('CSV Header: ', header)
    file = open(csvFileName, 'w', newline='')
    #with file:
    writer = csv.writer(file)
    writer.writerow(header)
    test_filenames= []
    for path, subdirs, files in os.walk(soundFilesFolder):
        for name in files:
        #print(os.path.join(path, name))
            test_filenames.append(os.path.join(path, name))
    
    
    
    
    for i in xfilenames:
        dirname, key  = get_sound_id_from_file_path(i)
        correlation = dirname.split('/')[-1]
        y, sr = librosa.load(i, mono=True, duration=30)
        
        # remove leading and trailing silence
        
        y, index = librosa.effects.trim(y)
        
        chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
        rmse = librosa.feature.rms(y=y)
        spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
        spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
        rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
        zcr = librosa.feature.zero_crossing_rate(y)
        mfcc = librosa.feature.mfcc(y=y, sr=sr)
        
        to_append = f' {key} {correlation} {np.mean(chroma_stft)} {np.mean(rmse)} {np.mean(spec_cent)} {np.mean(spec_bw)} {np.mean(rolloff)} {np.mean(zcr)}'
        for e in mfcc:
            to_append += f' {np.mean(e)}'
        writer.writerow(to_append.split())
    file.close()
    print("End of extractWavFeatures")

In [215]:
CREATE_CSV_FILES = True

In [216]:
#TRAIN_CSV_FILE = "D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/MFCC_train.csv"
#TEST_CSV_FILE = "D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/MFCC_test.csv"
#MORE_TRAIN_CSV_FILE = "C:/Users/Asus/Documents/COVID19/MFCC/test/more_train.csv"
#MORE_TEST_CSV_FILE = "C:/Users/Asus/Documents/COVID19/MFCC/test/more_test.csv"

In [217]:
TRAIN_CSV_FILE ='D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/50s_overlap_chunk_train_mfcc.csv'
TEST_CSV_FILE ='D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/50sec_chunk_test_mfcc.csv'

In [218]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
import librosa
import csv
import os



if (CREATE_CSV_FILES == True):
    extractWavFeatures("D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/train/", TRAIN_CSV_FILE, train_filenames)
    extractWavFeatures("D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/test/", TEST_CSV_FILE, test_filenames)
    #extractWavFeatures("C:/Users/Asus/Documents/COVID19/MFCC/moreSpeakersTrain", MORE_TRAIN_CSV_FILE)
    #extractWavFeatures("C:/Users/Asus/Documents/COVID19/MFCC/moreSpeakersTest", MORE_TEST_CSV_FILE)
    print("CSV files are created")
else:
    print("CSV files creation is skipped")

The features of the files in the folder D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/train/ will be saved to D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/50s_overlap_chunk_train_mfcc.csv
CSV Header:  ['key', 'correlation', 'chroma_stft', 'rmse', 'spectral_centroid', 'spectral_bandwidth', 'rolloff', 'zero_crossing_rate', 'mfcc1', 'mfcc2', 'mfcc3', 'mfcc4', 'mfcc5', 'mfcc6', 'mfcc7', 'mfcc8', 'mfcc9', 'mfcc10', 'mfcc11', 'mfcc12', 'mfcc13', 'mfcc14', 'mfcc15', 'mfcc16', 'mfcc17', 'mfcc18', 'mfcc19', 'mfcc20']


C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=376
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\pitch.py:153: UserWarning: Trying to estimate tuning from empty frequency set.
  warnings.warn("Trying to estimate tuning from empty frequency set.")
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=370
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=1054
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=1536
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=1878
  warnings.warn(
C

End of extractWavFeatures
The features of the files in the folder D:/COVID_COUGH_SOUNDS/50ms_overlap_458_aug_balanced/50S_overlap_aug_balanced_458/test/ will be saved to D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/50sec_chunk_test_mfcc.csv
CSV Header:  ['key', 'correlation', 'chroma_stft', 'rmse', 'spectral_centroid', 'spectral_bandwidth', 'rolloff', 'zero_crossing_rate', 'mfcc1', 'mfcc2', 'mfcc3', 'mfcc4', 'mfcc5', 'mfcc6', 'mfcc7', 'mfcc8', 'mfcc9', 'mfcc10', 'mfcc11', 'mfcc12', 'mfcc13', 'mfcc14', 'mfcc15', 'mfcc16', 'mfcc17', 'mfcc18', 'mfcc19', 'mfcc20']


C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=9
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=474
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=1504
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=1216
  warnings.warn(


End of extractWavFeatures
CSV files are created


In [232]:
import pandas as pd
train = pd.read_csv(TRAIN_CSV_FILE, sep=',')
test = pd.read_csv(TEST_CSV_FILE, sep=',')

In [233]:
#TRAIN_CSV_FILE

In [234]:
train

key correlation  chroma_stft      rmse  \
0            1591363379163_0.wav   allergies     0.524454  0.003503   
1            1591363379163_1.wav   allergies     0.416481  0.072161   
2            1591363379163_2.wav   allergies     0.412128  0.124396   
3            1591363379163_3.wav   allergies     0.487229  0.100306   
4            1591363379163_4.wav   allergies     0.556395  0.046316   
...                          ...         ...          ...       ...   
14793  1630617115433_speed_5.wav   pneumonia     0.504339  0.012863   
14794  1630617115433_speed_6.wav   pneumonia     0.528079  0.042942   
14795  1630617115433_speed_7.wav   pneumonia     0.468409  0.067464   
14796  1630617115433_speed_8.wav   pneumonia     0.441320  0.043443   
14797  1630617115433_speed_9.wav   pneumonia     0.465952  0.018882   

       spectral_centroid  spectral_bandwidth      rolloff  zero_crossing_rate  \
0            2159.131164         2021.219219  4512.918923            0.118974   
1            1924.665417         1918.047708  4037.230890            0.111439   
2            1448.453361         1732.121955  2947.112482            0.070756   
3            1350.369514         1639.811992  2715.875244            0.064997   
4            1938.944422         1911.583750  4136.087868            0.119385   
...                  ...                 ...          ...                 ...   
14793        3073.827712         2249.704110  5552.140669            0.251332   
14794        3406.895725         2304.867135  5833.540483            0.305054   
14795        2973.400900         2331.009117  5599.366899            0.227461   
14796        2768.314350         2264.346168  5305.487615            0.198497   
14797        3322.779120         2189.963843  5521.309038            0.291426   

            mfcc1       mfcc2  ...     mfcc11     mfcc12    mfcc13     mfcc14  \
0     -477.664673  116.399292  ...   9.357745 -13.794257  4.277086   6.179628   
1     -278.992035  114.890671  ...   8.243503 -18.375893 -2.123168   5.627200   
2     -201.681244  142.291702  ...   3.693502 -12.944245  7.432921  -3.477646   
3     -243.089661  145.864502  ...   6.954595 -11.851579  4.839436  -3.185500   
4     -316.657654  117.775612  ...  12.845105 -14.421775 -2.565778   0.730787   
...           ...         ...  ...        ...        ...       ...        ...   
14793 -380.690033   92.061943  ...  11.618156 -21.125475  4.719792 -10.954749   
14794 -313.244415   80.088020  ...   9.169736 -19.621975  7.770680  -9.857676   
14795 -233.976868  100.803879  ...  12.215497 -19.462446  3.570148  -6.762970   
14796 -279.545441   96.625977  ...  15.501517 -17.341478  0.088896  -2.183691   
14797 -355.480652   75.091972  ...  19.072374 -17.937035  1.796939  -1.905991   

          mfcc15     mfcc16     mfcc17     mfcc18    mfcc19    mfcc20  
0      16.248001  -2.214058  13.136648  -1.199873  3.703456 -2.345680  
1      11.845422  -4.261895   8.714609  -1.774737  1.929945 -1.497545  
2       5.489117 -11.890240   7.559861  -1.567741  1.874205 -3.009213  
3       4.177882 -11.189816   9.514095  -1.103271  1.849957 -3.752593  
4      10.888634  -6.457182  10.307930  -2.149672  3.143193 -3.106141  
...          ...        ...        ...        ...       ...       ...  
14793   2.640088  -4.810783   7.630625  -9.603418 -5.585784  0.499448  
14794   1.100204  -1.257298   4.083265  -7.945234 -5.332254 -3.031887  
14795   0.158452  -8.055977   5.682380  -8.689347 -1.617524 -6.976845  
14796  -0.465098 -10.659842   7.952493 -10.774840 -2.528926 -3.193502  
14797   1.633065  -3.226311   9.265835  -9.434379 -2.828412  2.701966  

[14798 rows x 28 columns]

In [235]:
import pandas as pd
#train = pd.read_csv(TRAIN_CSV_FILE)
test = pd.read_csv(TEST_CSV_FILE)

In [236]:
train[['filename','chunk']]= train['key'].str.split('_', 1, expand=True)

In [237]:
del train['chunk']

In [238]:
del train['key']

In [239]:
train['filename'] = pd.factorize(train['filename'])[0]

In [240]:
test[['filename','chunk']]= test['key'].str.split('_', 1, expand=True)
del test['chunk']
del test['key']
test['filename'] = pd.factorize(test['filename'])[0]

In [241]:
train

correlation  chroma_stft      rmse  spectral_centroid  \
0       allergies     0.524454  0.003503        2159.131164   
1       allergies     0.416481  0.072161        1924.665417   
2       allergies     0.412128  0.124396        1448.453361   
3       allergies     0.487229  0.100306        1350.369514   
4       allergies     0.556395  0.046316        1938.944422   
...           ...          ...       ...                ...   
14793   pneumonia     0.504339  0.012863        3073.827712   
14794   pneumonia     0.528079  0.042942        3406.895725   
14795   pneumonia     0.468409  0.067464        2973.400900   
14796   pneumonia     0.441320  0.043443        2768.314350   
14797   pneumonia     0.465952  0.018882        3322.779120   

       spectral_bandwidth      rolloff  zero_crossing_rate       mfcc1  \
0             2021.219219  4512.918923            0.118974 -477.664673   
1             1918.047708  4037.230890            0.111439 -278.992035   
2             1732.121955  2947.112482            0.070756 -201.681244   
3             1639.811992  2715.875244            0.064997 -243.089661   
4             1911.583750  4136.087868            0.119385 -316.657654   
...                   ...          ...                 ...         ...   
14793         2249.704110  5552.140669            0.251332 -380.690033   
14794         2304.867135  5833.540483            0.305054 -313.244415   
14795         2331.009117  5599.366899            0.227461 -233.976868   
14796         2264.346168  5305.487615            0.198497 -279.545441   
14797         2189.963843  5521.309038            0.291426 -355.480652   

            mfcc2      mfcc3  ...     mfcc12    mfcc13     mfcc14     mfcc15  \
0      116.399292 -35.718052  ... -13.794257  4.277086   6.179628  16.248001   
1      114.890671 -16.514809  ... -18.375893 -2.123168   5.627200  11.845422   
2      142.291702 -13.531425  ... -12.944245  7.432921  -3.477646   5.489117   
3      145.864502 -14.255789  ... -11.851579  4.839436  -3.185500   4.177882   
4      117.775612 -16.894743  ... -14.421775 -2.565778   0.730787  10.888634   
...           ...        ...  ...        ...       ...        ...        ...   
14793   92.061943  -2.006695  ... -21.125475  4.719792 -10.954749   2.640088   
14794   80.088020   0.164812  ... -19.621975  7.770680  -9.857676   1.100204   
14795  100.803879  -8.398238  ... -19.462446  3.570148  -6.762970   0.158452   
14796   96.625977  -2.246640  ... -17.341478  0.088896  -2.183691  -0.465098   
14797   75.091972   2.533186  ... -17.937035  1.796939  -1.905991   1.633065   

          mfcc16     mfcc17     mfcc18    mfcc19    mfcc20  filename  
0      -2.214058  13.136648  -1.199873  3.703456 -2.345680         0  
1      -4.261895   8.714609  -1.774737  1.929945 -1.497545         0  
2     -11.890240   7.559861  -1.567741  1.874205 -3.009213         0  
3     -11.189816   9.514095  -1.103271  1.849957 -3.752593         0  
4      -6.457182  10.307930  -2.149672  3.143193 -3.106141         0  
...          ...        ...        ...       ...       ...       ...  
14793  -4.810783   7.630625  -9.603418 -5.585784  0.499448       222  
14794  -1.257298   4.083265  -7.945234 -5.332254 -3.031887       222  
14795  -8.055977   5.682380  -8.689347 -1.617524 -6.976845       222  
14796 -10.659842   7.952493 -10.774840 -2.528926 -3.193502       222  
14797  -3.226311   9.265835  -9.434379 -2.828412  2.701966       222  

[14798 rows x 28 columns]

In [242]:
train['correlation'].value_counts()

covid        3496
other        3329
allergies    3196
asthma       3012
pneumonia    1765
Name: correlation, dtype: int64

In [243]:
test['correlation'].value_counts()

allergies    724
asthma       723
covid        720
pneumonia    719
other        716
Name: correlation, dtype: int64

In [244]:
test['correlation'] = pd.factorize(test['correlation'])[0]
train['correlation'] = pd.factorize(train['correlation'])[0]

In [245]:
#test['correlation'] = pd.factorize(test['correlation'])[0]
#train['correlation'] = pd.factorize(train['correlation'])[0]

In [246]:
print(test['correlation'].value_counts())

0    724
1    723
2    720
4    719
3    716
Name: correlation, dtype: int64


In [247]:
print(train['correlation'].value_counts())

2    3496
3    3329
0    3196
1    3012
4    1765
Name: correlation, dtype: int64


In [215]:
print(train['correlation'].value_counts())

0    402
1    402
2    402
3    402
4    402
Name: correlation, dtype: int64


In [216]:
train

key  correlation  chroma_stft      rmse  \
0      1603442347486_0.wav            0     0.779478  0.050193   
1      1603442347486_1.wav            0     0.800904  0.055082   
2     1603442347486_10.wav            0     0.691474  0.050547   
3     1603442347486_11.wav            0     0.621796  0.181249   
4     1603442347486_12.wav            0     0.660660  0.094073   
...                    ...          ...          ...       ...   
2005   1630617115433_5.wav            4     0.444425  0.023013   
2006   1630617115433_6.wav            4     0.505653  0.119977   
2007   1630617115433_7.wav            4     0.536779  0.041179   
2008   1630617115433_8.wav            4     0.534310  0.010082   
2009   1630617115433_9.wav            4     0.700734  0.000765   

      spectral_centroid  spectral_bandwidth      rolloff  zero_crossing_rate  \
0            288.115039          956.156227   343.797164            0.005338   
1            246.709718          907.607949   308.071622            0.003862   
2            486.465407         1267.644157   655.049827            0.012218   
3            675.724274         1475.475237   892.404452            0.023970   
4            685.049033         1522.721219   979.516047            0.022550   
...                 ...                 ...          ...                 ...   
2005        3639.753819         2180.388180  5734.928200            0.339733   
2006        2884.002752         2244.268240  5440.804221            0.217973   
2007        2108.092036         2088.558477  4426.296720            0.124589   
2008        2217.294166         2170.542242  5091.134366            0.129339   
2009        2418.572046         2199.186517  5167.234664            0.150524   

           mfcc1       mfcc2  ...     mfcc11     mfcc12     mfcc13    mfcc14  \
0    -459.645386  157.449661  ...   0.715976   8.376441   3.719340  4.041049   
1    -473.697754  168.211227  ...  -1.403503   9.627779   3.585397  3.124698   
2    -438.937286  197.820740  ...  -3.653198   9.197322  -1.360180 -7.469585   
3    -282.934753  237.248398  ... -16.875116   5.986283   1.521341 -3.543556   
4    -382.796509  214.092667  ... -18.986876  17.577335  16.530235  1.527412   
...          ...         ...  ...        ...        ...        ...       ...   
2005 -330.096893   73.816681  ...  21.229221 -16.492153   3.575610 -3.322581   
2006 -199.996872  100.093414  ...   8.759502 -13.416610   2.739661 -5.376436   
2007 -407.798462   86.235962  ...   3.708232  -3.259722  -6.056814  5.396718   
2008 -451.308197  102.238205  ...   5.554382  -7.539816   1.751220 -3.567297   
2009 -554.512756  112.171600  ...   5.259885  -6.422646   6.069443 -5.910280   

         mfcc15     mfcc16     mfcc17     mfcc18     mfcc19    mfcc20  
0     12.679458   4.364612  11.424557  -0.944280  10.070965  5.323479  
1     11.207709   2.163931  13.495655  -0.912194  11.822683  2.729552  
2     13.803504 -10.306087  12.609823 -10.798158  12.737912  4.062510  
3     22.567749 -20.424252  16.937799 -12.147681  17.494648 -5.419091  
4     16.672031 -18.643141  20.070513  -7.721399  19.674316 -0.521447  
...         ...        ...        ...        ...        ...       ...  
2005   0.922660  -3.946052   9.622485  -7.541713  -1.207176  2.338977  
2006   0.059222  -7.374077   4.818901  -9.290490  -0.376637 -6.540622  
2007  -0.937791  -4.265805  -0.282950  -7.957600  -1.122818 -3.469936  
2008  -3.127809  -6.305748   6.980862  -7.857993  -4.228704  1.524270  
2009   7.465800  -6.288251   7.775389  -7.316936   2.681150 -1.879824  

[2010 rows x 28 columns]

MACHINE LEARNING

In [393]:
corr = [0, 1]
train_2 = train[train.correlation.isin(corr)]
test_2 = test[test.correlation.isin(corr)]

In [394]:
train_2

correlation  chroma_stft      rmse  spectral_centroid  \
0               0     0.524454  0.003503        2159.131164   
1               0     0.416481  0.072161        1924.665417   
2               0     0.412128  0.124396        1448.453361   
3               0     0.487229  0.100306        1350.369514   
4               0     0.556395  0.046316        1938.944422   
...           ...          ...       ...                ...   
6203            1     0.406757  0.061758        1967.954183   
6204            1     0.481684  0.031792        2293.513012   
6205            1     0.580898  0.003907        2475.555519   
6206            1     0.476085  0.061203        2206.545463   
6207            1     0.366365  0.121387        1993.931079   

      spectral_bandwidth      rolloff  zero_crossing_rate       mfcc1  \
0            2021.219219  4512.918923            0.118974 -477.664673   
1            1918.047708  4037.230890            0.111439 -278.992035   
2            1732.121955  2947.112482            0.070756 -201.681244   
3            1639.811992  2715.875244            0.064997 -243.089661   
4            1911.583750  4136.087868            0.119385 -316.657654   
...                  ...          ...                 ...         ...   
6203         2006.887565  4443.180708            0.116588 -301.456421   
6204         2080.574816  4810.468639            0.145153 -320.589447   
6205         2202.895769  5376.449308            0.146440 -442.384796   
6206         2067.191284  4800.680819            0.114557 -348.704681   
6207         1899.093008  4252.339504            0.097762 -202.604324   

           mfcc2      mfcc3  ...     mfcc12     mfcc13    mfcc14     mfcc15  \
0     116.399292 -35.718052  ... -13.794257   4.277086  6.179628  16.248001   
1     114.890671 -16.514809  ... -18.375893  -2.123168  5.627200  11.845422   
2     142.291702 -13.531425  ... -12.944245   7.432921 -3.477646   5.489117   
3     145.864502 -14.255789  ... -11.851579   4.839436 -3.185500   4.177882   
4     117.775612 -16.894743  ... -14.421775  -2.565778  0.730787  10.888634   
...          ...        ...  ...        ...        ...       ...        ...   
6203  114.468971  -9.609836  ... -12.037444   6.284280  1.156817  -2.243653   
6204  104.806229 -15.380502  ... -11.770211   5.311013  2.793022   5.720740   
6205  121.189697 -44.462090  ...  -6.597923  10.473542 -3.860429  14.497650   
6206   85.906052 -15.124312  ...  -0.769904   8.479465  2.133707  13.336059   
6207  110.540482 -43.442177  ...  -3.155507  13.933608 -1.592143  23.204849   

         mfcc16     mfcc17    mfcc18    mfcc19    mfcc20  filename  
0     -2.214058  13.136648 -1.199873  3.703456 -2.345680         0  
1     -4.261895   8.714609 -1.774737  1.929945 -1.497545         0  
2    -11.890240   7.559861 -1.567741  1.874205 -3.009213         0  
3    -11.189816   9.514095 -1.103271  1.849957 -3.752593         0  
4     -6.457182  10.307930 -2.149672  3.143193 -3.106141         0  
...         ...        ...       ...       ...       ...       ...  
6203 -12.608789   7.266687 -2.270951  4.438255  6.756147       119  
6204  -7.478619   5.386984 -1.412912  0.152065  0.549805       119  
6205  -6.710127  10.330288 -3.803692  5.537288 -4.420136       119  
6206   3.702840   7.067152 -1.673600 -2.856332  2.869330       119  
6207   2.167193   9.005527 -6.622405 -6.564704  5.726299       119  

[6208 rows x 28 columns]

In [395]:
#train_2

In [396]:
X_train = train_2.loc[:, train_2.columns!='correlation']
X_test = test_2.loc[:, test_2.columns!='correlation']
y_train  = train_2['correlation']
y_test = test_2['correlation']

In [397]:
#X_train

In [398]:
del X_train['filename']
del X_test['filename']

In [399]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train= ms.fit_transform(X_train)
X_train = pd.DataFrame(X_train)

X_test= ms.fit_transform(X_test)
X_test = pd.DataFrame(X_test)

In [400]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn import metrics
model =SVC()
model.fit (X_train, y_train)
svm_pred = model.predict(X_test)
print ('SVM accuracy: ', accuracy_score (y_test, svm_pred))
confusion_matrix(y_test,svm_pred )

SVM accuracy:  0.4948168624740843


array([[393, 331],
       [400, 323]], dtype=int64)

In [401]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier


clf = MLPClassifier(random_state=1,hidden_layer_sizes=3, max_iter=1000).fit(X_train, y_train)
#clf.predict_proba(X_test)

mlp_pred = clf.predict(X_test)

print('MLP accuracy: ',clf.score(X_test, y_test))
confusion_matrix(y_test, mlp_pred )

MLP accuracy:  0.5134761575673807


array([[567, 157],
       [547, 176]], dtype=int64)

In [402]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
print ('Random forest Accuracy: ', accuracy_score (y_test, rf_pred))
#predict_cough_type = rf.predict(X_test)
#print ('Accuracy: ', accuracy_score (y_test, predict_cough_type))

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, rf_pred)

Random forest Accuracy:  0.5114029025570145


array([[468, 256],
       [451, 272]], dtype=int64)

In [403]:
true_test_values = test_2.loc[:, ['filename','correlation']]
keys = true_test_values.filename.unique()
true_test_values['SVM prediction'] = svm_pred
true_test_values['MLP prediction'] = mlp_pred
true_test_values['RF prediction'] = rf_pred
#true_test_values['SVM prediction'] = svm_pred
#true_test_values['SVM prediction'] = y_pred
true_test_values

filename  correlation  SVM prediction  MLP prediction  RF prediction
0            0            0               0               0              1
1            0            0               0               0              0
2            0            0               0               0              0
3            0            0               1               0              0
4            0            0               0               0              0
...        ...          ...             ...             ...            ...
1442        15            1               1               0              1
1443        15            1               1               0              1
1444        15            1               1               0              1
1445        15            1               0               0              0
1446        15            1               1               0              1

[1447 rows x 5 columns]

In [404]:
#true_test_values = test_2.loc[:, ['filename','correlation']]
#keys = true_test_values.filename.unique()
#true_test_values['SVM prediction'] = y_pred
#true_test_values['SVM prediction'] = y_pred
#true_test_values

In [405]:
#for i in keys:
    #print(i)

In [406]:
from scipy.stats import mode

Mode = []
Mode2 = []
Mode3 = []
Mode4 = []

for i in keys:
    m = true_test_values[true_test_values['filename']==i]['correlation'].values
    m2 = true_test_values[true_test_values['filename']==i]['SVM prediction'].values
    m3 = true_test_values[true_test_values['filename']==i]['MLP prediction'].values
    m4 = true_test_values[true_test_values['filename']==i]['RF prediction'].values
    
    #print(m)
    
    s = mode(m)[0]
    s2 = mode(m2)[0]
    s3 = mode(m3)[0]
    s4 = mode(m4)[0]
    #print(s)
    
    Mode.append(s[0])
    Mode2.append(s2[0])
    Mode3.append(s3[0])
    Mode4.append(s4[0])

In [407]:
svm_list = []
mlp_list = []
rf_list = []
for i in range(len(Mode)):
    for j in range(len(Mode2)):
        if (i==j):
            if (Mode[i]==Mode2[j]):
                svm_list.append(i)
            if (Mode[i]==Mode3[j]):
                mlp_list.append(i)
            if (Mode[i]==Mode4[j]):
                rf_list.append(i)

In [408]:
#17/83
SVM_score = len(svm_list)/len(Mode2)
print('SVM Accuracy score of chunks after voting:',SVM_score)
MLP_score = len(mlp_list)/len(Mode2)
print('MLP Accuracy score of chunks after voting:',MLP_score)
RF_score = len(rf_list)/len(Mode2)
print('RF Accuracy score of chunks after voting:',RF_score)

SVM Accuracy score of chunks after voting: 0.5
MLP Accuracy score of chunks after voting: 0.5
RF Accuracy score of chunks after voting: 0.5


In [156]:
import pandas as pd
import os
import numpy as np
np.set_printoptions(precision=4)
import catboost
from catboost import *
from catboost import datasets
from catboost import CatBoostClassifier
model_Cat_boost = CatBoostClassifier(#task_type ='GPU',
                                    iterations = 20,
                                    random_state =2021)
                                    #eval_metric ='F1')

In [157]:
model_Cat_boost.fit(X_train, y_train, #plot ='True',
                   eval_set =(X_test, y_test))
from sklearn.metrics import accuracy_score
y_pred  = model_Cat_boost.predict(X_test)
accuracy_score(y_test, y_pred)

Learning rate set to 0.164649
0:	learn: 0.6540425	test: 0.6654616	best: 0.6654616 (0)	total: 162ms	remaining: 3.07s
1:	learn: 0.6258333	test: 0.6534476	best: 0.6534476 (1)	total: 166ms	remaining: 1.5s
2:	learn: 0.5987010	test: 0.6609820	best: 0.6534476 (1)	total: 171ms	remaining: 971ms
3:	learn: 0.5857537	test: 0.6620594	best: 0.6534476 (1)	total: 176ms	remaining: 704ms
4:	learn: 0.5618583	test: 0.6592674	best: 0.6534476 (1)	total: 181ms	remaining: 543ms
5:	learn: 0.5477708	test: 0.6801327	best: 0.6534476 (1)	total: 186ms	remaining: 434ms
6:	learn: 0.5286591	test: 0.6779323	best: 0.6534476 (1)	total: 191ms	remaining: 356ms
7:	learn: 0.5109796	test: 0.6933329	best: 0.6534476 (1)	total: 196ms	remaining: 293ms
8:	learn: 0.4984299	test: 0.6894782	best: 0.6534476 (1)	total: 200ms	remaining: 244ms
9:	learn: 0.4870210	test: 0.6895413	best: 0.6534476 (1)	total: 204ms	remaining: 204ms
10:	learn: 0.4784905	test: 0.7010724	best: 0.6534476 (1)	total: 208ms	remaining: 170ms
11:	learn: 0.4662537	tes

0.625

BALANCED DATASET

In [183]:
print(train['correlation'].value_counts())

3    460
2    360
1    208
0    172
4     88
Name: correlation, dtype: int64


In [184]:
print(test['correlation'].value_counts())

3    192
2    152
1     88
0     76
4     36
Name: correlation, dtype: int64


In [226]:
new_df = train.sample(frac=1, random_state =4)

# Separate class
class_0 = new_df[new_df ['correlation'] == 0].sample(n= 172, random_state =42)
class_1 = new_df[new_df ['correlation'] == 1].sample(n= 208, random_state =42)
class_2 = new_df[new_df ['correlation'] == 2].sample(n= 172, random_state =42)
class_3 = new_df[new_df ['correlation'] == 3].sample(n= 172, random_state =42)
class_4 = new_df[new_df ['correlation'] == 4].sample(n= 88, random_state =42)

In [227]:
balanced_train  = pd.concat([class_0, class_1, class_2, class_3, class_4])

In [228]:
print(test['correlation'].value_counts())

3    192
2    152
1     88
0     76
4     36
Name: correlation, dtype: int64


In [229]:
new_df = test.sample(frac=1, random_state =4)

# Separate class
class_0 = new_df[new_df ['correlation'] == 0].sample(n= 76, random_state =42)
class_1 = new_df[new_df ['correlation'] == 1].sample(n= 88, random_state =42)
class_2 = new_df[new_df ['correlation'] == 2].sample(n= 88, random_state =42)
class_3 = new_df[new_df ['correlation'] == 3].sample(n= 88, random_state =42)
class_4 = new_df[new_df ['correlation'] == 4].sample(n= 36, random_state =42)

In [230]:
balanced_test  = pd.concat([class_0, class_1, class_2, class_3, class_4])

In [231]:
print(balanced_test['correlation'].value_counts())
print(balanced_train['correlation'].value_counts())

1    88
2    88
3    88
0    76
4    36
Name: correlation, dtype: int64
1    208
0    172
2    172
3    172
4     88
Name: correlation, dtype: int64


In [232]:
X_train = balanced_train.loc[:, balanced_train.columns!='correlation']
X_test = balanced_test.loc[:, balanced_test.columns!='correlation']
y_train  = balanced_train['correlation']
y_test = balanced_test['correlation']

In [233]:
del X_train['key']
del X_test['key']

In [234]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train= ms.fit_transform(X_train)
X_train = pd.DataFrame(X_train)

X_test= ms.fit_transform(X_test)
X_test = pd.DataFrame(X_test)

In [235]:
model =SVC()
model.fit (X_train, y_train)
y_pred = model.predict(X_test)
print ('SVM accuracy: ', accuracy_score (y_test, y_pred))

SVM accuracy:  0.21808510638297873


In [236]:
clf = MLPClassifier(random_state=1, max_iter=2000).fit(X_train, y_train)
#clf.predict_proba(X_test)

clf.predict(X_test)

print('MLP accuracy: ',clf.score(X_test, y_test))

MLP accuracy:  0.26595744680851063


In [237]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(X_train, y_train)

RandomForestClassifier()

In [238]:
predict_cough_type = rf.predict(X_test)
print ('Accuracy: ', accuracy_score (y_test, predict_cough_type))
#predict_cough_type = rf.predict(X_test)
#print ('Accuracy: ', accuracy_score (y_test, predict_cough_type))

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predict_cough_type)
## confusion matrix

Accuracy:  0.24202127659574468


array([[10, 26, 17, 23,  0],
       [11, 37, 15, 23,  2],
       [10, 35, 21, 21,  1],
       [17, 33, 17, 21,  0],
       [ 3,  7,  6, 18,  2]], dtype=int64)

In [239]:
from sklearn.tree import DecisionTreeClassifier
dec_tree_classifier  = DecisionTreeClassifier (max_leaf_nodes = 10, random_state =0)
dec_tree_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [240]:
y_predicted  = dec_tree_classifier.predict(X_test)

In [241]:
accuracy_score(y_test, y_predicted)*100

22.340425531914892

In [242]:
import pandas as pd
import os
import numpy as np
np.set_printoptions(precision=4)
import catboost
from catboost import *
from catboost import datasets

In [243]:
import catboost

from catboost import CatBoostClassifier

In [244]:
model_Cat_boost = CatBoostClassifier(#task_type ='GPU',
                                    iterations = 20,
                                    random_state =2021)
                                    #eval_metric ='F1')

In [245]:
model_Cat_boost.fit(X_train, y_train, plot ='True',
                   eval_set =(X_test, y_test))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.47921
0:	learn: 1.4952140	test: 1.5926795	best: 1.5926795 (0)	total: 13ms	remaining: 248ms
1:	learn: 1.4305778	test: 1.6007032	best: 1.5926795 (0)	total: 24.9ms	remaining: 225ms
2:	learn: 1.3612212	test: 1.6219610	best: 1.5926795 (0)	total: 38.2ms	remaining: 217ms
3:	learn: 1.2914811	test: 1.6457481	best: 1.5926795 (0)	total: 50.3ms	remaining: 201ms
4:	learn: 1.2479166	test: 1.6595692	best: 1.5926795 (0)	total: 62.4ms	remaining: 187ms
5:	learn: 1.2088818	test: 1.6729226	best: 1.5926795 (0)	total: 76.7ms	remaining: 179ms
6:	learn: 1.1596237	test: 1.6875599	best: 1.5926795 (0)	total: 88.8ms	remaining: 165ms
7:	learn: 1.1051763	test: 1.7042438	best: 1.5926795 (0)	total: 102ms	remaining: 152ms
8:	learn: 1.0687560	test: 1.7157231	best: 1.5926795 (0)	total: 113ms	remaining: 139ms
9:	learn: 1.0401517	test: 1.7324013	best: 1.5926795 (0)	total: 125ms	remaining: 125ms
10:	learn: 0.9920159	test: 1.7610686	best: 1.5926795 (0)	total: 137ms	remaining: 112ms
11:	learn: 0.956513

In [246]:
from sklearn.metrics import accuracy_score
y_pred  = model_Cat_boost.predict(X_test)
accuracy_score(y_test, y_pred)

0.2632978723404255

In [247]:
from xgboost import XGBClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report, accuracy_score
import xgboost


#xgb = XGBClassifier(use_label_encoder =False)
xgb = xgboost.XGBClassifier(num_class=5,
                            use_label_encoder =False,
                                  learning_rate=0.1,
                                  num_iterations=1000,
                                  max_depth=10,
                                  feature_fraction=0.7, 
                                  scale_pos_weight=1.5,
                                  boosting='gbdt',
                                  metric='multiclass',
                                  eval_metric='mlogloss')
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)

xgb.fit(X_train, y_train)
y_pred = xgb.predict(np.asarray(X_test))
y_pred = [round(value) for value in y_pred]
print('Accuracy score:' + str(accuracy_score(y_test, y_pred)))
print('F1 score:' + str(f1_score(y_test, y_pred, average = 'weighted')))
print(confusion_matrix(y_test, y_pred))

[18:53:25] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576: 
Parameters: { "boosting", "feature_fraction", "metric", "num_iterations", "scale_pos_weight" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


Accuracy score:0.23138297872340424
F1 score:0.2203921042270621
[[15 20 16 21  4]
 [13 32 16 26  1]
 [10 28 20 28  2]
 [16 29 22 20  1]
 [ 3 10  7 16  0]]


In [248]:
## One class classification

In [249]:
#y_train

In [304]:
corr = [0,3]
train_2 = balanced_train[balanced_train.correlation.isin(corr)]
test_2 = balanced_test[balanced_test.correlation.isin(corr)]


X_train = train_2.loc[:, train_2.columns != 'correlation']
y_train = train_2['correlation']

X_test = test_2.loc[:, test_2.columns != 'correlation']
y_test = test_2['correlation']

del X_train['key']
del X_test['key']


In [305]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X_train= ms.fit_transform(X_train)
X_train = pd.DataFrame(X_train)

X_test = ms.fit_transform(X_test)
X_test = pd.DataFrame(X_test)

#X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)


In [306]:
model =SVC()
model.fit (X_train, y_train)
y_pred = model.predict(X_test)

print(model.score(X_test, y_test))
confusion_matrix(y_test,y_pred )

0.4451219512195122


array([[24, 52],
       [39, 49]], dtype=int64)

In [307]:
clf = MLPClassifier(random_state=1, max_iter=2000).fit(X_train, y_train)
#clf.predict_proba(X_test)

y_pred = clf.predict(X_test)

print(clf.score(X_test, y_test))
confusion_matrix(y_test,y_pred )

0.43902439024390244


C:\Users\salta\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


array([[38, 38],
       [54, 34]], dtype=int64)

In [308]:
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print(rf.score(X_test, y_test))
confusion_matrix(y_test,y_pred )

0.5121951219512195


array([[33, 43],
       [37, 51]], dtype=int64)

In [309]:
model_Cat_boost.fit(X_train, y_train)
y_pred = model_Cat_boost.predict(X_test)
model_Cat_boost.score(X_test, y_test)

Learning rate set to 0.236048
0:	learn: 0.6222954	total: 34ms	remaining: 646ms
1:	learn: 0.5548661	total: 36.6ms	remaining: 329ms
2:	learn: 0.5259299	total: 39.2ms	remaining: 222ms
3:	learn: 0.4681088	total: 41.9ms	remaining: 168ms
4:	learn: 0.4287697	total: 44.6ms	remaining: 134ms
5:	learn: 0.3958234	total: 47.7ms	remaining: 111ms
6:	learn: 0.3750424	total: 50.3ms	remaining: 93.3ms
7:	learn: 0.3356160	total: 52.9ms	remaining: 79.4ms
8:	learn: 0.3110454	total: 55.5ms	remaining: 67.9ms
9:	learn: 0.2967370	total: 58.1ms	remaining: 58.1ms
10:	learn: 0.2801574	total: 61ms	remaining: 49.9ms
11:	learn: 0.2616368	total: 63.8ms	remaining: 42.6ms
12:	learn: 0.2477860	total: 67.1ms	remaining: 36.2ms
13:	learn: 0.2360415	total: 70.1ms	remaining: 30.1ms
14:	learn: 0.2313453	total: 72.8ms	remaining: 24.3ms
15:	learn: 0.2199976	total: 75.6ms	remaining: 18.9ms
16:	learn: 0.2098675	total: 78.5ms	remaining: 13.9ms
17:	learn: 0.1984637	total: 81.3ms	remaining: 9.04ms
18:	learn: 0.1861914	total: 84.4ms	r

0.4573170731707317