In [1]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
import librosa
import csv
import os
from glob import glob

In [2]:
root = 'D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/train'
#root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/train'
train_filenames= []
for path, subdirs, files in os.walk(root):
    for name in files:
        #print(os.path.join(path, name))
        test_filenames.append(os.path.join(path, name))

In [3]:
#DATA_DIR='D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP+COUGHVID_CHUNKS_50_OVERLAP/allergies/'
#filenames =glob(DATA_DIR + '/*.wav')

In [ ]:
root_t = 'D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/test'
#root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/train'
test_filenames= []
for path, subdirs, files in os.walk(root):
    for name in files:
        #print(os.path.join(path, name))
        test_filenames.append(os.path.join(path, name))

In [4]:
def load_audio_file(file_path):
    input_length = 16000
    data = librosa.core.load(file_path)[0] #, sr=16000
    return data

In [5]:
def get_data_files():
    # we will be leaving some files out, on purpose. Do not change this function!
    return [os.path.join(DATA_DIR, x) for x in sorted(os.listdir(DATA_DIR)) ]

In [6]:
def get_sound_id_from_file_path(file_path):
    a = file_path.split('\\')[-2:]
    return a

In [7]:
print(test_filenames[1])
correlation, key = get_sound_id_from_file_path(test_filenames[1])
print(correlation)
print(key)

D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/train\allergie\1604907203513_noise.wav
allergie
1604907203513_noise.wav


In [26]:
def extractWavFeatures(soundFilesFolder, csvFileName):
    print("The features of the files in the folder "+soundFilesFolder+" will be saved to "+csvFileName)
    header = 'key correlation chroma_stft rmse spectral_centroid spectral_bandwidth rolloff zero_crossing_rate'
    for i in range(1, 21):
        header += f' mfcc{i}'
    #header += ' label'
    header = header.split()
    print('CSV Header: ', header)
    file = open(csvFileName, 'w', newline='')
    #with file:
    writer = csv.writer(file)
    writer.writerow(header)
    test_filenames= []
    for path, subdirs, files in os.walk(soundFilesFolder):
        for name in files:
        #print(os.path.join(path, name))
            test_filenames.append(os.path.join(path, name))
    
    
    
    
    for i in test_filenames:
        correlation, key  = get_sound_id_from_file_path(i)
        y, sr = librosa.load(i, mono=True, duration=30)
        
        # remove leading and trailing silence
        
        y, index = librosa.effects.trim(y)
        
        chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
        rmse = librosa.feature.rms(y=y)
        spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
        spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
        rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
        zcr = librosa.feature.zero_crossing_rate(y)
        mfcc = librosa.feature.mfcc(y=y, sr=sr)
        
        to_append = f' {key} {correlation} {np.mean(chroma_stft)} {np.mean(rmse)} {np.mean(spec_cent)} {np.mean(spec_bw)} {np.mean(rolloff)} {np.mean(zcr)}'
        for e in mfcc:
            to_append += f' {np.mean(e)}'
        writer.writerow(to_append.split())
    file.close()
    print("End of extractWavFeatures")

In [28]:
CREATE_CSV_FILES = True

In [29]:
#TRAIN_CSV_FILE = "D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/MFCC_train.csv"
#TEST_CSV_FILE = "D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/MFCC_test.csv"
#MORE_TRAIN_CSV_FILE = "C:/Users/Asus/Documents/COVID19/MFCC/test/more_train.csv"
#MORE_TEST_CSV_FILE = "C:/Users/Asus/Documents/COVID19/MFCC/test/more_test.csv"

In [30]:
TRAIN_CSV_FILE ='D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/MFCC_full_sounds_augmented_train.csv'
TEST_CSV_FILE ='D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/MFCC_full_sounds_augmented_test.csv'

In [31]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
import librosa
import csv
import os



if (CREATE_CSV_FILES == True):
    extractWavFeatures("D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/train", TRAIN_CSV_FILE)
    extractWavFeatures("D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/test", TEST_CSV_FILE)
    #extractWavFeatures("C:/Users/Asus/Documents/COVID19/MFCC/moreSpeakersTrain", MORE_TRAIN_CSV_FILE)
    #extractWavFeatures("C:/Users/Asus/Documents/COVID19/MFCC/moreSpeakersTest", MORE_TEST_CSV_FILE)
    print("CSV files are created")
else:
    print("CSV files creation is skipped")

The features of the files in the folder D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/train will be saved to D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/MFCC_full_sounds_augmented_train.csv
CSV Header:  ['key', 'correlation', 'chroma_stft', 'rmse', 'spectral_centroid', 'spectral_bandwidth', 'rolloff', 'zero_crossing_rate', 'mfcc1', 'mfcc2', 'mfcc3', 'mfcc4', 'mfcc5', 'mfcc6', 'mfcc7', 'mfcc8', 'mfcc9', 'mfcc10', 'mfcc11', 'mfcc12', 'mfcc13', 'mfcc14', 'mfcc15', 'mfcc16', 'mfcc17', 'mfcc18', 'mfcc19', 'mfcc20']


C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=1536
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\pitch.py:153: UserWarning: Trying to estimate tuning from empty frequency set.
  warnings.warn("Trying to estimate tuning from empty frequency set.")
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=512
  warnings.warn(
C:\Users\salta\anaconda3\lib\site-packages\librosa\core\spectrum.py:222: UserWarning: n_fft=2048 is too small for input signal of length=1024
  warnings.warn(


End of extractWavFeatures
The features of the files in the folder D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/test will be saved to D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/MFCC_full_sounds_augmented_test.csv
CSV Header:  ['key', 'correlation', 'chroma_stft', 'rmse', 'spectral_centroid', 'spectral_bandwidth', 'rolloff', 'zero_crossing_rate', 'mfcc1', 'mfcc2', 'mfcc3', 'mfcc4', 'mfcc5', 'mfcc6', 'mfcc7', 'mfcc8', 'mfcc9', 'mfcc10', 'mfcc11', 'mfcc12', 'mfcc13', 'mfcc14', 'mfcc15', 'mfcc16', 'mfcc17', 'mfcc18', 'mfcc19', 'mfcc20']
End of extractWavFeatures
CSV files are created


In [88]:
import pandas as pd
train = pd.read_csv('D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/MFCC_full_sounds_augmented_train.csv')
test = pd.read_csv('D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP_AUGMENTED/MFCC_full_sounds_augmented_test.csv')

In [89]:
#TRAIN_CSV_FILE

In [90]:
train

key correlation  chroma_stft      rmse  \
0           1604907203513.wav    allergie     0.432197  0.073355   
1     1604907203513_noise.wav    allergie     0.486210  0.074436   
2     1604907203513_pitch.wav    allergie     0.430796  0.073597   
3     1604907203513_speed.wav    allergie     0.421420  0.050867   
4           1604907385918.wav    allergie     0.541133  0.055551   
...                       ...         ...          ...       ...   
1283  1630616718338_speed.wav   pneumonia     0.457624  0.027622   
1284        1630617115433.wav   pneumonia     0.584458  0.031397   
1285  1630617115433_noise.wav   pneumonia     0.654994  0.033826   
1286  1630617115433_pitch.wav   pneumonia     0.583084  0.031397   
1287  1630617115433_speed.wav   pneumonia     0.557503  0.021751   

      spectral_centroid  spectral_bandwidth      rolloff  zero_crossing_rate  \
0           2175.196143         1866.410416  4435.485679            0.149588   
1           3437.321883         2697.644797  6569.220693            0.249361   
2           2186.035607         1883.675555  4449.733379            0.149791   
3           2158.539130         1885.908299  4411.048327            0.145733   
4           3130.061088         2179.030479  5839.616814            0.250052   
...                 ...                 ...          ...                 ...   
1283        3295.463422         2198.273017  5637.084961            0.295627   
1284        2729.347819         2165.068375  5283.031261            0.210778   
1285        4673.575600         3024.473089  8200.602911            0.400177   
1286        2749.851229         2199.117541  5309.726048            0.210778   
1287        2746.107457         2227.771925  5349.319876            0.207090   

           mfcc1       mfcc2  ...    mfcc11     mfcc12    mfcc13    mfcc14  \
0    -248.372589  100.145203  ...  1.195061 -13.322680  8.263878 -6.620495   
1    -180.269150   56.818462  ... -0.660479  -6.604637  2.771005 -0.609252   
2    -247.376083  100.469582  ...  1.214169 -13.350938  8.308656 -6.621794   
3    -274.595642  108.333664  ...  0.597516 -14.853464  7.752444 -8.209581   
4    -267.074188   65.771973  ...  0.387622   0.400475  7.596847 -8.065909   
...          ...         ...  ...       ...        ...       ...       ...   
1283 -344.152313   78.793083  ...  7.188071 -20.427433  3.779288 -2.880576   
1284 -382.096680   69.093529  ...  7.653633  -8.993364  1.251557 -1.090024   
1285 -256.577423   20.748068  ...  3.460560  -4.911588 -0.762806  0.237131   
1286 -382.027649   69.025192  ...  7.672158  -8.971796  1.255161 -1.060921   
1287 -413.805115   71.465279  ...  6.625015 -10.120228  1.643504 -1.478818   

         mfcc15    mfcc16    mfcc17     mfcc18     mfcc19    mfcc20  
0     11.089859 -5.957028  0.502174  -5.043720 -10.276903 -1.263781  
1      6.086140 -1.775576 -0.867594  -2.497383  -7.830077 -0.410429  
2     11.154837 -5.946504  0.534692  -5.029052 -10.281414 -1.238396  
3     11.458509 -7.547943  1.435923  -4.907001  -9.092078 -0.978365  
4     18.416906 -9.924283  3.372713  -2.170714   3.568209 -3.027963  
...         ...       ...       ...        ...        ...       ...  
1283  -2.020188 -4.196573  3.170312 -11.372537   2.945531 -2.876136  
1284  -1.326393 -2.525375  3.213384  -4.866541  -1.889130 -1.435676  
1285  -2.721034 -0.125764  0.069649  -2.407052  -1.529707 -1.377709  
1286  -1.327451 -2.496363  3.211230  -4.834787  -1.885533 -1.414546  
1287  -1.581104 -2.966957  3.226786  -5.393914  -1.849913 -1.176207  

[1288 rows x 28 columns]

In [91]:
test

key correlation  chroma_stft      rmse  \
0          1591363379163.wav    allergie     0.476973  0.061352   
1    1591363379163_noise.wav    allergie     0.602019  0.062348   
2    1591363379163_pitch.wav    allergie     0.479765  0.040955   
3    1591363379163_speed.wav    allergie     0.480533  0.041968   
4          1591422756659.wav    allergie     0.431883  0.024943   
..                       ...         ...          ...       ...   
539  1604840684793_speed.wav   pneumonia     0.423835  0.036048   
540        1604903187610.wav   pneumonia     0.524054  0.038413   
541  1604903187610_noise.wav   pneumonia     0.600181  0.039339   
542  1604903187610_pitch.wav   pneumonia     0.529309  0.018917   
543  1604903187610_speed.wav   pneumonia     0.507786  0.027123   

     spectral_centroid  spectral_bandwidth      rolloff  zero_crossing_rate  \
0          1637.137038         1743.452008  3412.962618            0.089480   
1          3807.411280         2958.063241  7291.464339            0.287160   
2          1572.067567         1694.570288  3244.026552            0.085300   
3          1764.346995         1874.407889  3607.009682            0.099849   
4          1999.750318         1764.192437  4104.199219            0.129484   
..                 ...                 ...          ...                 ...   
539        3087.552427         1924.777090  5147.470797            0.273876   
540         578.233347         1333.735771   758.670702            0.020053   
541        3794.726407         3387.802794  7984.946380            0.156047   
542         656.174433         1505.314910   849.374949            0.022762   
543         608.321431         1407.553554   775.882277            0.021719   

          mfcc1       mfcc2  ...     mfcc11     mfcc12    mfcc13    mfcc14  \
0   -323.624969  107.401718  ...   2.413419 -11.156631  1.898175 -0.322627   
1   -224.668732   52.914837  ...   1.157628  -6.147384 -1.023789  1.276554   
2   -354.148834  117.005508  ...  14.665513  -7.840634 -3.938224 -4.953007   
3   -345.042023  109.391342  ...   6.139168 -12.223216  1.907579  1.336822   
4   -406.951172   80.524200  ...  -9.108408  -5.347715 -1.964847 -5.651423   
..          ...         ...  ...        ...        ...       ...       ...   
539 -305.952789   82.477524  ...   6.913932 -13.058589  1.947110 -5.047692   
540 -393.864563  110.978989  ...   3.845689   4.569818  2.487446 -0.741276   
541 -270.573547   47.715126  ...   3.498620   3.539809  3.082884  0.847034   
542 -467.618011  113.901176  ...   1.470037   5.189247 -0.415622  1.352847   
543 -439.361633  118.539581  ...   3.680830   4.628007  1.991610 -1.470668   

       mfcc15     mfcc16    mfcc17     mfcc18    mfcc19    mfcc20  
0    5.292337  -4.246020  7.508950   0.116339  2.128314 -2.224436  
1    2.396752  -1.128284  3.286006   1.118902  0.347389 -1.222623  
2    5.054475   1.359681 -2.304963   7.378729 -0.513810  6.990722  
3    6.544016  -5.018676  8.363056   0.104561  2.637770 -3.746327  
4   -3.889395  -4.578368  1.167199 -16.026226 -8.168590 -3.305593  
..        ...        ...       ...        ...       ...       ...  
539  1.188978 -19.949867  1.044482  -7.213414 -1.918879 -1.438352  
540  4.879114  -5.085642  0.539506  -1.667372  6.197483  4.449610  
541  2.388403  -1.516334  0.702613   0.516060  3.538648  2.587666  
542  3.402065  -4.388654  3.293478   0.302943  8.239042 -1.237721  
543  5.576470  -6.030171  0.476423  -2.791699  6.373467  4.263284  

[544 rows x 28 columns]

In [92]:
train['correlation'].value_counts()

other        460
covid        360
asthma       208
allergie     172
pneumonia     88
Name: correlation, dtype: int64

In [93]:
test['correlation'].value_counts()

other        192
covid        152
asthma        88
allergie      76
pneumonia     36
Name: correlation, dtype: int64

In [94]:
test['correlation'] = pd.factorize(test['correlation'])[0]
train['correlation'] = pd.factorize(train['correlation'])[0]

In [95]:
print(test['correlation'].value_counts())

3    192
2    152
1     88
0     76
4     36
Name: correlation, dtype: int64


In [96]:
print(train['correlation'].value_counts())

3    460
2    360
1    208
0    172
4     88
Name: correlation, dtype: int64


In [97]:
print(train['correlation'].value_counts())

3    460
2    360
1    208
0    172
4     88
Name: correlation, dtype: int64


In [98]:
train

key  correlation  chroma_stft      rmse  \
0           1604907203513.wav            0     0.432197  0.073355   
1     1604907203513_noise.wav            0     0.486210  0.074436   
2     1604907203513_pitch.wav            0     0.430796  0.073597   
3     1604907203513_speed.wav            0     0.421420  0.050867   
4           1604907385918.wav            0     0.541133  0.055551   
...                       ...          ...          ...       ...   
1283  1630616718338_speed.wav            4     0.457624  0.027622   
1284        1630617115433.wav            4     0.584458  0.031397   
1285  1630617115433_noise.wav            4     0.654994  0.033826   
1286  1630617115433_pitch.wav            4     0.583084  0.031397   
1287  1630617115433_speed.wav            4     0.557503  0.021751   

      spectral_centroid  spectral_bandwidth      rolloff  zero_crossing_rate  \
0           2175.196143         1866.410416  4435.485679            0.149588   
1           3437.321883         2697.644797  6569.220693            0.249361   
2           2186.035607         1883.675555  4449.733379            0.149791   
3           2158.539130         1885.908299  4411.048327            0.145733   
4           3130.061088         2179.030479  5839.616814            0.250052   
...                 ...                 ...          ...                 ...   
1283        3295.463422         2198.273017  5637.084961            0.295627   
1284        2729.347819         2165.068375  5283.031261            0.210778   
1285        4673.575600         3024.473089  8200.602911            0.400177   
1286        2749.851229         2199.117541  5309.726048            0.210778   
1287        2746.107457         2227.771925  5349.319876            0.207090   

           mfcc1       mfcc2  ...    mfcc11     mfcc12    mfcc13    mfcc14  \
0    -248.372589  100.145203  ...  1.195061 -13.322680  8.263878 -6.620495   
1    -180.269150   56.818462  ... -0.660479  -6.604637  2.771005 -0.609252   
2    -247.376083  100.469582  ...  1.214169 -13.350938  8.308656 -6.621794   
3    -274.595642  108.333664  ...  0.597516 -14.853464  7.752444 -8.209581   
4    -267.074188   65.771973  ...  0.387622   0.400475  7.596847 -8.065909   
...          ...         ...  ...       ...        ...       ...       ...   
1283 -344.152313   78.793083  ...  7.188071 -20.427433  3.779288 -2.880576   
1284 -382.096680   69.093529  ...  7.653633  -8.993364  1.251557 -1.090024   
1285 -256.577423   20.748068  ...  3.460560  -4.911588 -0.762806  0.237131   
1286 -382.027649   69.025192  ...  7.672158  -8.971796  1.255161 -1.060921   
1287 -413.805115   71.465279  ...  6.625015 -10.120228  1.643504 -1.478818   

         mfcc15    mfcc16    mfcc17     mfcc18     mfcc19    mfcc20  
0     11.089859 -5.957028  0.502174  -5.043720 -10.276903 -1.263781  
1      6.086140 -1.775576 -0.867594  -2.497383  -7.830077 -0.410429  
2     11.154837 -5.946504  0.534692  -5.029052 -10.281414 -1.238396  
3     11.458509 -7.547943  1.435923  -4.907001  -9.092078 -0.978365  
4     18.416906 -9.924283  3.372713  -2.170714   3.568209 -3.027963  
...         ...       ...       ...        ...        ...       ...  
1283  -2.020188 -4.196573  3.170312 -11.372537   2.945531 -2.876136  
1284  -1.326393 -2.525375  3.213384  -4.866541  -1.889130 -1.435676  
1285  -2.721034 -0.125764  0.069649  -2.407052  -1.529707 -1.377709  
1286  -1.327451 -2.496363  3.211230  -4.834787  -1.885533 -1.414546  
1287  -1.581104 -2.966957  3.226786  -5.393914  -1.849913 -1.176207  

[1288 rows x 28 columns]

MACHINE LEARNING

In [174]:
corr = [0, 3]
train_2 = train[train.correlation.isin(corr)]
test_2 = test[test.correlation.isin(corr)]

In [175]:
#train_2

In [176]:
X_train = train_2.loc[:, train_2.columns!='correlation']
X_test = test_2.loc[:, test_2.columns!='correlation']
y_train  = train_2['correlation']
y_test = test_2['correlation']

In [177]:
#X_train

In [178]:
del X_train['key']
del X_test['key']

In [179]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train= ms.fit_transform(X_train)
X_train = pd.DataFrame(X_train)

X_test= ms.fit_transform(X_test)
X_test = pd.DataFrame(X_test)

In [180]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn import metrics
model =SVC()
model.fit (X_train, y_train)
y_pred = model.predict(X_test)
print ('SVM accuracy: ', accuracy_score (y_test, y_pred))
confusion_matrix(y_test,y_pred )

SVM accuracy:  0.6902985074626866


array([[ 11,  65],
       [ 18, 174]], dtype=int64)

In [181]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier


clf = MLPClassifier(random_state=1, max_iter=2000).fit(X_train, y_train)
#clf.predict_proba(X_test)

clf.predict(X_test)

print('MLP accuracy: ',clf.score(X_test, y_test))
confusion_matrix(y_test,y_pred )

MLP accuracy:  0.5223880597014925


array([[ 11,  65],
       [ 18, 174]], dtype=int64)

In [182]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(X_train, y_train)
predict_cough_type = rf.predict(X_test)
print ('Accuracy: ', accuracy_score (y_test, predict_cough_type))
#predict_cough_type = rf.predict(X_test)
#print ('Accuracy: ', accuracy_score (y_test, predict_cough_type))

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predict_cough_type)

Accuracy:  0.6007462686567164


array([[  5,  71],
       [ 36, 156]], dtype=int64)

In [77]:
import pandas as pd
import os
import numpy as np
np.set_printoptions(precision=4)
import catboost
from catboost import *
from catboost import datasets
from catboost import CatBoostClassifier
model_Cat_boost = CatBoostClassifier(#task_type ='GPU',
                                    iterations = 20,
                                    random_state =2021)
                                    #eval_metric ='F1')

In [78]:
model_Cat_boost.fit(X_train, y_train, #plot ='True',
                   eval_set =(X_test, y_test))
from sklearn.metrics import accuracy_score
y_pred  = model_Cat_boost.predict(X_test)
accuracy_score(y_test, y_pred)

Learning rate set to 0.483652
0:	learn: 1.4107285	test: 1.5647452	best: 1.5647452 (0)	total: 19.7ms	remaining: 374ms
1:	learn: 1.3095183	test: 1.5772105	best: 1.5647452 (0)	total: 32.3ms	remaining: 290ms
2:	learn: 1.2582246	test: 1.5819555	best: 1.5647452 (0)	total: 44.7ms	remaining: 253ms
3:	learn: 1.1951295	test: 1.5924593	best: 1.5647452 (0)	total: 65.2ms	remaining: 261ms
4:	learn: 1.1648491	test: 1.5836666	best: 1.5647452 (0)	total: 80.1ms	remaining: 240ms
5:	learn: 1.1292492	test: 1.5979380	best: 1.5647452 (0)	total: 94ms	remaining: 219ms
6:	learn: 1.0967536	test: 1.6081653	best: 1.5647452 (0)	total: 107ms	remaining: 199ms
7:	learn: 1.0569746	test: 1.6408014	best: 1.5647452 (0)	total: 119ms	remaining: 179ms
8:	learn: 1.0049608	test: 1.6559230	best: 1.5647452 (0)	total: 132ms	remaining: 161ms
9:	learn: 0.9747779	test: 1.6742056	best: 1.5647452 (0)	total: 146ms	remaining: 146ms
10:	learn: 0.9504972	test: 1.6958887	best: 1.5647452 (0)	total: 159ms	remaining: 130ms
11:	learn: 0.923230

0.28860294117647056

BALANCED DATASET

In [183]:
print(train['correlation'].value_counts())

3    460
2    360
1    208
0    172
4     88
Name: correlation, dtype: int64


In [184]:
print(test['correlation'].value_counts())

3    192
2    152
1     88
0     76
4     36
Name: correlation, dtype: int64


In [226]:
new_df = train.sample(frac=1, random_state =4)

# Separate class
class_0 = new_df[new_df ['correlation'] == 0].sample(n= 172, random_state =42)
class_1 = new_df[new_df ['correlation'] == 1].sample(n= 208, random_state =42)
class_2 = new_df[new_df ['correlation'] == 2].sample(n= 172, random_state =42)
class_3 = new_df[new_df ['correlation'] == 3].sample(n= 172, random_state =42)
class_4 = new_df[new_df ['correlation'] == 4].sample(n= 88, random_state =42)

In [227]:
balanced_train  = pd.concat([class_0, class_1, class_2, class_3, class_4])

In [228]:
print(test['correlation'].value_counts())

3    192
2    152
1     88
0     76
4     36
Name: correlation, dtype: int64


In [229]:
new_df = test.sample(frac=1, random_state =4)

# Separate class
class_0 = new_df[new_df ['correlation'] == 0].sample(n= 76, random_state =42)
class_1 = new_df[new_df ['correlation'] == 1].sample(n= 88, random_state =42)
class_2 = new_df[new_df ['correlation'] == 2].sample(n= 88, random_state =42)
class_3 = new_df[new_df ['correlation'] == 3].sample(n= 88, random_state =42)
class_4 = new_df[new_df ['correlation'] == 4].sample(n= 36, random_state =42)

In [230]:
balanced_test  = pd.concat([class_0, class_1, class_2, class_3, class_4])

In [231]:
print(balanced_test['correlation'].value_counts())
print(balanced_train['correlation'].value_counts())

1    88
2    88
3    88
0    76
4    36
Name: correlation, dtype: int64
1    208
0    172
2    172
3    172
4     88
Name: correlation, dtype: int64


In [232]:
X_train = balanced_train.loc[:, balanced_train.columns!='correlation']
X_test = balanced_test.loc[:, balanced_test.columns!='correlation']
y_train  = balanced_train['correlation']
y_test = balanced_test['correlation']

In [233]:
del X_train['key']
del X_test['key']

In [234]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train= ms.fit_transform(X_train)
X_train = pd.DataFrame(X_train)

X_test= ms.fit_transform(X_test)
X_test = pd.DataFrame(X_test)

In [235]:
model =SVC()
model.fit (X_train, y_train)
y_pred = model.predict(X_test)
print ('SVM accuracy: ', accuracy_score (y_test, y_pred))

SVM accuracy:  0.21808510638297873


In [236]:
clf = MLPClassifier(random_state=1, max_iter=2000).fit(X_train, y_train)
#clf.predict_proba(X_test)

clf.predict(X_test)

print('MLP accuracy: ',clf.score(X_test, y_test))

MLP accuracy:  0.26595744680851063


In [237]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(X_train, y_train)

RandomForestClassifier()

In [238]:
predict_cough_type = rf.predict(X_test)
print ('Accuracy: ', accuracy_score (y_test, predict_cough_type))
#predict_cough_type = rf.predict(X_test)
#print ('Accuracy: ', accuracy_score (y_test, predict_cough_type))

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predict_cough_type)
## confusion matrix

Accuracy:  0.24202127659574468


array([[10, 26, 17, 23,  0],
       [11, 37, 15, 23,  2],
       [10, 35, 21, 21,  1],
       [17, 33, 17, 21,  0],
       [ 3,  7,  6, 18,  2]], dtype=int64)

In [239]:
from sklearn.tree import DecisionTreeClassifier
dec_tree_classifier  = DecisionTreeClassifier (max_leaf_nodes = 10, random_state =0)
dec_tree_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [240]:
y_predicted  = dec_tree_classifier.predict(X_test)

In [241]:
accuracy_score(y_test, y_predicted)*100

22.340425531914892

In [242]:
import pandas as pd
import os
import numpy as np
np.set_printoptions(precision=4)
import catboost
from catboost import *
from catboost import datasets

In [243]:
import catboost

from catboost import CatBoostClassifier

In [244]:
model_Cat_boost = CatBoostClassifier(#task_type ='GPU',
                                    iterations = 20,
                                    random_state =2021)
                                    #eval_metric ='F1')

In [245]:
model_Cat_boost.fit(X_train, y_train, plot ='True',
                   eval_set =(X_test, y_test))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.47921
0:	learn: 1.4952140	test: 1.5926795	best: 1.5926795 (0)	total: 13ms	remaining: 248ms
1:	learn: 1.4305778	test: 1.6007032	best: 1.5926795 (0)	total: 24.9ms	remaining: 225ms
2:	learn: 1.3612212	test: 1.6219610	best: 1.5926795 (0)	total: 38.2ms	remaining: 217ms
3:	learn: 1.2914811	test: 1.6457481	best: 1.5926795 (0)	total: 50.3ms	remaining: 201ms
4:	learn: 1.2479166	test: 1.6595692	best: 1.5926795 (0)	total: 62.4ms	remaining: 187ms
5:	learn: 1.2088818	test: 1.6729226	best: 1.5926795 (0)	total: 76.7ms	remaining: 179ms
6:	learn: 1.1596237	test: 1.6875599	best: 1.5926795 (0)	total: 88.8ms	remaining: 165ms
7:	learn: 1.1051763	test: 1.7042438	best: 1.5926795 (0)	total: 102ms	remaining: 152ms
8:	learn: 1.0687560	test: 1.7157231	best: 1.5926795 (0)	total: 113ms	remaining: 139ms
9:	learn: 1.0401517	test: 1.7324013	best: 1.5926795 (0)	total: 125ms	remaining: 125ms
10:	learn: 0.9920159	test: 1.7610686	best: 1.5926795 (0)	total: 137ms	remaining: 112ms
11:	learn: 0.956513

In [246]:
from sklearn.metrics import accuracy_score
y_pred  = model_Cat_boost.predict(X_test)
accuracy_score(y_test, y_pred)

0.2632978723404255

In [247]:
from xgboost import XGBClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report, accuracy_score
import xgboost


#xgb = XGBClassifier(use_label_encoder =False)
xgb = xgboost.XGBClassifier(num_class=5,
                            use_label_encoder =False,
                                  learning_rate=0.1,
                                  num_iterations=1000,
                                  max_depth=10,
                                  feature_fraction=0.7, 
                                  scale_pos_weight=1.5,
                                  boosting='gbdt',
                                  metric='multiclass',
                                  eval_metric='mlogloss')
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)

xgb.fit(X_train, y_train)
y_pred = xgb.predict(np.asarray(X_test))
y_pred = [round(value) for value in y_pred]
print('Accuracy score:' + str(accuracy_score(y_test, y_pred)))
print('F1 score:' + str(f1_score(y_test, y_pred, average = 'weighted')))
print(confusion_matrix(y_test, y_pred))

[18:53:25] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:576: 
Parameters: { "boosting", "feature_fraction", "metric", "num_iterations", "scale_pos_weight" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


Accuracy score:0.23138297872340424
F1 score:0.2203921042270621
[[15 20 16 21  4]
 [13 32 16 26  1]
 [10 28 20 28  2]
 [16 29 22 20  1]
 [ 3 10  7 16  0]]


In [248]:
## One class classification

In [249]:
#y_train

In [304]:
corr = [0,3]
train_2 = balanced_train[balanced_train.correlation.isin(corr)]
test_2 = balanced_test[balanced_test.correlation.isin(corr)]


X_train = train_2.loc[:, train_2.columns != 'correlation']
y_train = train_2['correlation']

X_test = test_2.loc[:, test_2.columns != 'correlation']
y_test = test_2['correlation']

del X_train['key']
del X_test['key']


In [305]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X_train= ms.fit_transform(X_train)
X_train = pd.DataFrame(X_train)

X_test = ms.fit_transform(X_test)
X_test = pd.DataFrame(X_test)

#X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)


In [306]:
model =SVC()
model.fit (X_train, y_train)
y_pred = model.predict(X_test)

print(model.score(X_test, y_test))
confusion_matrix(y_test,y_pred )

0.4451219512195122


array([[24, 52],
       [39, 49]], dtype=int64)

In [307]:
clf = MLPClassifier(random_state=1, max_iter=2000).fit(X_train, y_train)
#clf.predict_proba(X_test)

y_pred = clf.predict(X_test)

print(clf.score(X_test, y_test))
confusion_matrix(y_test,y_pred )

0.43902439024390244


C:\Users\salta\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


array([[38, 38],
       [54, 34]], dtype=int64)

In [308]:
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print(rf.score(X_test, y_test))
confusion_matrix(y_test,y_pred )

0.5121951219512195


array([[33, 43],
       [37, 51]], dtype=int64)

In [309]:
model_Cat_boost.fit(X_train, y_train)
y_pred = model_Cat_boost.predict(X_test)
model_Cat_boost.score(X_test, y_test)

Learning rate set to 0.236048
0:	learn: 0.6222954	total: 34ms	remaining: 646ms
1:	learn: 0.5548661	total: 36.6ms	remaining: 329ms
2:	learn: 0.5259299	total: 39.2ms	remaining: 222ms
3:	learn: 0.4681088	total: 41.9ms	remaining: 168ms
4:	learn: 0.4287697	total: 44.6ms	remaining: 134ms
5:	learn: 0.3958234	total: 47.7ms	remaining: 111ms
6:	learn: 0.3750424	total: 50.3ms	remaining: 93.3ms
7:	learn: 0.3356160	total: 52.9ms	remaining: 79.4ms
8:	learn: 0.3110454	total: 55.5ms	remaining: 67.9ms
9:	learn: 0.2967370	total: 58.1ms	remaining: 58.1ms
10:	learn: 0.2801574	total: 61ms	remaining: 49.9ms
11:	learn: 0.2616368	total: 63.8ms	remaining: 42.6ms
12:	learn: 0.2477860	total: 67.1ms	remaining: 36.2ms
13:	learn: 0.2360415	total: 70.1ms	remaining: 30.1ms
14:	learn: 0.2313453	total: 72.8ms	remaining: 24.3ms
15:	learn: 0.2199976	total: 75.6ms	remaining: 18.9ms
16:	learn: 0.2098675	total: 78.5ms	remaining: 13.9ms
17:	learn: 0.1984637	total: 81.3ms	remaining: 9.04ms
18:	learn: 0.1861914	total: 84.4ms	r

0.4573170731707317