In [118]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
import librosa
import csv
import os
from glob import glob

In [161]:
import os

# Absolute path of a file
old_name = r"D:\balanced_1s_not_aug\1s_balancedChunks\train\ff\1603942345102x_0.wav"
new_name = r"D:\balanced_1s_not_aug\1s_balancedChunks\train\ff\1603942345102_0.wav"

# Renaming the file
os.rename(old_name, new_name)

In [180]:
root = 'D:/balanced_1s_not_aug/1s_balancedChunks/test/ss/'
#root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/train'
renam_filenames= []
for path, subdirs, files in os.walk(root):
    for name in files:
        #print(os.path.join(path, name))
        renam_filenames.append(os.path.join(path, name))

In [181]:
len(renam_filenames)

61

In [186]:
new_names =  []
for i in range(len(renam_filenames)):
    a = renam_filenames[i].split('/')[-1]
    s = a[:13] + "b" + a[13:]
    new_names.append(s)
    #print(s)

In [183]:
path = 'D:/balanced_1s_not_aug/1s_balancedChunks/test/ss/'
new_filenames= []

for name in new_names:
        #print(os.path.join(path, name))
        new_filenames.append(os.path.join(path, name))

In [184]:
for i in range(len(renam_filenames)):
    os.rename(renam_filenames[i], new_filenames[i])

In [185]:
len(new_filenames)

61

In [171]:
a = renam_filenames[1].split('/')[-1]
s = a[:13] + "b" + a[13:]
print(a, s)

1603942345102_1.wav 1603942345102b_1.wav


In [ ]:
s = a[:13] + "b" + a[13:]

In [187]:
new_names =  []
for i in range(len(renam_filenames)):
    a = renam_filenames[i].split('/')[-1]
    s = a[:13] + "b" + a[13:]
    new_names.append(s)
    #print(s)

In [188]:
root = 'D:/balanced_1s_not_aug/1s_balancedChunks/train/'
#root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/train'
train_filenames= []
for path, subdirs, files in os.walk(root):
    for name in files:
        #print(os.path.join(path, name))
        train_filenames.append(os.path.join(path, name))

In [189]:
#DATA_DIR='D:/COVID_COUGH_SOUNDS/DATASET_FINAL/WEBAPP+COUGHVID_CHUNKS_50_OVERLAP/allergies/'
#filenames =glob(DATA_DIR + '/*.wav')

In [190]:
root_t = 'D:/balanced_1s_not_aug/1s_balancedChunks/test/'
#root = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/train'
test_filenames= []
for path, subdirs, files in os.walk(root_t):
    for name in files:
        #print(os.path.join(path, name))
        test_filenames.append(os.path.join(path, name))

In [192]:
test_filenames[-104]

'D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/test/pneumonia\\1595212847994b_0.wav'

In [193]:
def load_audio_file(file_path):
    input_length = 16000
    data = librosa.core.load(file_path)[0] #, sr=16000
    return data

In [194]:
def get_data_files():
    # we will be leaving some files out, on purpose. Do not change this function!
    return [os.path.join(DATA_DIR, x) for x in sorted(os.listdir(DATA_DIR)) ]

In [195]:
def get_sound_id_from_file_path(file_path):
    a = file_path.split('\\')[-2:]
    #b= file_path.split('/')[-1:]
    #c= file_path.split('\\')[-1:]
    return a
    #return a, b

In [196]:
print(test_filenames[1])
correlation, key = get_sound_id_from_file_path(test_filenames[1])
correlation, key = get_sound_id_from_file_path(test_filenames[1])
d = correlation.split('/')[-1]
print(correlation)
print(key)
print(d)

D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/test/allergies\1591363379163_1.wav
D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/test/allergies
1591363379163_1.wav
allergies


In [198]:
len(train_filenames)

2010

In [199]:
correlation

'D:/COVID_COUGH_SOUNDS/1second_chunks_458/balanced_1s_not_aug/1s_balancedChunks/test/allergies'

In [200]:
def extractWavFeatures(soundFilesFolder, csvFileName, xfilenames):
    print("The features of the files in the folder "+soundFilesFolder+" will be saved to "+csvFileName)
    header = 'key correlation chroma_stft rmse spectral_centroid spectral_bandwidth rolloff zero_crossing_rate'
    for i in range(1, 21):
        header += f' mfcc{i}'
    #header += ' label'
    header = header.split()
    print('CSV Header: ', header)
    file = open(csvFileName, 'w', newline='')
    #with file:
    writer = csv.writer(file)
    writer.writerow(header)
    test_filenames= []
    for path, subdirs, files in os.walk(soundFilesFolder):
        for name in files:
        #print(os.path.join(path, name))
            test_filenames.append(os.path.join(path, name))
    
    
    
    
    for i in xfilenames:
        dirname, key  = get_sound_id_from_file_path(i)
        correlation = dirname.split('/')[-1]
        y, sr = librosa.load(i, mono=True, duration=30)
        
        # remove leading and trailing silence
        
        y, index = librosa.effects.trim(y)
        
        chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
        rmse = librosa.feature.rms(y=y)
        spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
        spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
        rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
        zcr = librosa.feature.zero_crossing_rate(y)
        mfcc = librosa.feature.mfcc(y=y, sr=sr)
        
        to_append = f' {key} {correlation} {np.mean(chroma_stft)} {np.mean(rmse)} {np.mean(spec_cent)} {np.mean(spec_bw)} {np.mean(rolloff)} {np.mean(zcr)}'
        for e in mfcc:
            to_append += f' {np.mean(e)}'
        writer.writerow(to_append.split())
    file.close()
    print("End of extractWavFeatures")

In [201]:
CREATE_CSV_FILES = True

In [131]:
#TRAIN_CSV_FILE = "D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/MFCC_train.csv"
#TEST_CSV_FILE = "D:/COVID_COUGH_SOUNDS/1second_chunks_458/NON_AUGMENTED_1_SEC_CHUNKS_NO_OVERLAP/MFCC_test.csv"
#MORE_TRAIN_CSV_FILE = "C:/Users/Asus/Documents/COVID19/MFCC/test/more_train.csv"
#MORE_TEST_CSV_FILE = "C:/Users/Asus/Documents/COVID19/MFCC/test/more_test.csv"

In [202]:
TRAIN_CSV_FILE ='D:/balanced_1s_not_aug/1s_balancedChunks/1sec_chunk_train_mfcc.csv'
TEST_CSV_FILE ='D:/balanced_1s_not_aug/1s_balancedChunks/1sec_chunk_test_mfcc.csv'

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
import librosa
import csv
import os



if (CREATE_CSV_FILES == True):
    extractWavFeatures("D:/balanced_1s_not_aug/1s_balancedChunks/train/", TRAIN_CSV_FILE, train_filenames)
    extractWavFeatures("D:/balanced_1s_not_aug/1s_balancedChunks/test/", TEST_CSV_FILE, test_filenames)
    #extractWavFeatures("C:/Users/Asus/Documents/COVID19/MFCC/moreSpeakersTrain", MORE_TRAIN_CSV_FILE)
    #extractWavFeatures("C:/Users/Asus/Documents/COVID19/MFCC/moreSpeakersTest", MORE_TEST_CSV_FILE)
    print("CSV files are created")
else:
    print("CSV files creation is skipped")

In [204]:
import pandas as pd
train = pd.read_csv(TRAIN_CSV_FILE, sep=',')
test = pd.read_csv(TEST_CSV_FILE, sep=',')

In [205]:
#TRAIN_CSV_FILE

In [1]:
#train

In [207]:
import pandas as pd
#train = pd.read_csv(TRAIN_CSV_FILE)
test = pd.read_csv(TEST_CSV_FILE)

In [228]:
train[['filename','chunk']]= train['key'].str.split('_', 1, expand=True)

In [230]:
del train['chunk']

In [233]:
del train['key']

In [232]:
train['filename'] = pd.factorize(train['filename'])[0]

In [235]:
test[['filename','chunk']]= test['key'].str.split('_', 1, expand=True)
del test['chunk']
del test['key']
test['filename'] = pd.factorize(test['filename'])[0]

In [2]:
#test

In [210]:
train['correlation'].value_counts()

allergies    402
asthma       402
covid        402
other        402
pneumonia    402
Name: correlation, dtype: int64

In [211]:
test['correlation'].value_counts()

allergies    104
asthma       104
covid        104
other        104
pneumonia    104
Name: correlation, dtype: int64

In [212]:
#test['correlation'] = pd.factorize(test['correlation'])[0]
#train['correlation'] = pd.factorize(train['correlation'])[0]

In [213]:
print(test['correlation'].value_counts())

0    104
1    104
2    104
3    104
4    104
Name: correlation, dtype: int64


In [214]:
print(train['correlation'].value_counts())

0    402
1    402
2    402
3    402
4    402
Name: correlation, dtype: int64


In [215]:
print(train['correlation'].value_counts())

0    402
1    402
2    402
3    402
4    402
Name: correlation, dtype: int64


In [4]:
#train[:10]

MACHINE LEARNING

In [249]:
corr = [0, 1]
train_2 = train[train.correlation.isin(corr)]
test_2 = test[test.correlation.isin(corr)]

In [5]:
#train_2

In [250]:
#train_2

In [266]:
X_train = train_2.loc[:, train_2.columns!='correlation']
X_test = test_2.loc[:, test_2.columns!='correlation']
y_train  = train_2['correlation']
y_test = test_2['correlation']

In [267]:
#X_train

In [268]:
del X_train['filename']
del X_test['filename']

In [269]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train= ms.fit_transform(X_train)
X_train = pd.DataFrame(X_train)

X_test= ms.fit_transform(X_test)
X_test = pd.DataFrame(X_test)

In [270]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn import metrics
model =SVC()
model.fit (X_train, y_train)
svm_pred = model.predict(X_test)
print ('SVM accuracy: ', accuracy_score (y_test, svm_pred))
confusion_matrix(y_test,svm_pred )

SVM accuracy:  0.5336538461538461


array([[56, 48],
       [49, 55]], dtype=int64)

In [271]:
true_test_values = test_2.loc[:, ['filename','correlation']]
keys = true_test_values.filename.unique()
true_test_values['SVM prediction'] = svm_pred
#true_test_values['SVM prediction'] = y_pred
true_test_values

filename  correlation  SVM prediction
0           0            0               1
1           0            0               1
2           0            0               1
3           0            0               1
4           0            0               1
..        ...          ...             ...
203        24            1               0
204        24            1               0
205        24            1               0
206        24            1               0
207        24            1               0

[208 rows x 3 columns]

In [272]:
from scipy.stats import mode

Mode = []
Mode2 = []

for i in keys:
    m = true_test_values[true_test_values['filename']==i]['correlation'].values
    m2 = true_test_values[true_test_values['filename']==i]['SVM prediction'].values
    
    #print(m)
    
    s = mode(m)[0]
    s2 = mode(m2)[0]
    
    Mode.append(s[0])
    Mode2.append(s2[0])

In [273]:
new_list = []
for i in range(len(Mode)):
    for j in range(len(Mode2)):
        if (i==j):
            if (Mode[i]==Mode2[j]):
                new_list.append(i)

In [274]:
#17/83
score = len(new_list)/len(Mode2)
print('Accuracy score of chunks after voting:',score)

Accuracy score of chunks after voting: 0.4


In [275]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier


clf = MLPClassifier(random_state=1, max_iter=2000).fit(X_train, y_train)
#clf.predict_proba(X_test)

clf.predict(X_test)

print('MLP accuracy: ',clf.score(X_test, y_test))
confusion_matrix(y_test,y_pred )

MLP accuracy:  0.5865384615384616


array([[84, 20],
       [14, 90]], dtype=int64)

In [276]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(X_train, y_train)
predict_cough_type = rf.predict(X_test)
print ('Random forest Accuracy: ', accuracy_score (y_test, predict_cough_type))
#predict_cough_type = rf.predict(X_test)
#print ('Accuracy: ', accuracy_score (y_test, predict_cough_type))

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predict_cough_type)

Random forest Accuracy:  0.5625


array([[62, 42],
       [49, 55]], dtype=int64)