In [45]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from torch import nn
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt
import numpy as np
import tensorboard
import torchvision
from torch.utils.tensorboard import SummaryWriter
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))
from sklearn.model_selection import KFold

Using cuda device


In [46]:
transform = transforms.Compose(
            [transforms.Resize([224, 224]),
    transforms.ToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))])

In [47]:
train_dataset = datasets.ImageFolder(root='D:/COVID_COUGH_SOUNDS/50S_overlap_458/50ms_stft_images/train', 
                                     transform=transform)
test_dataset  = datasets.ImageFolder(root='D:/COVID_COUGH_SOUNDS/50S_overlap_458/50ms_stft_images/test',  
                                     transform=transform)
#valid_dataset  = datasets.ImageFolder(root='D:/split_data_breast/val',  
                                     #transform=transform)

In [48]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=4, shuffle=True)

In [18]:
count=0
for i in range(len(train_dataset.targets)):
    if train_dataset.targets[i]==1:
        train_dataloader.dataset[i]
        count+=1
print(count)

452


In [14]:
train_dataset.targets[560]

1

In [22]:
train_dataloader.dataset[560]

(tensor([[[2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          ...,
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
          [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489]],
 
         [[2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          ...,
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
          [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286]],
 
         [[2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
          [2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
          [2.6400, 2.6400, 2.6400,  ...,

In [19]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=4, shuffle=True)

In [35]:
train_dataloader

In [4]:
train_dataset.classes

['allergies', 'asthma', 'covid', 'other', 'pneumonia']

In [5]:
train_dataset.class_to_idx

{'allergies': 0, 'asthma': 1, 'covid': 2, 'other': 3, 'pneumonia': 4}

In [6]:
test_dataset.class_to_idx

{'allergies': 0, 'asthma': 1, 'covid': 2, 'other': 3, 'pneumonia': 4}

In [15]:
#train_dataset.targets

In [17]:
idx

False

In [80]:
train_dataset

Dataset ImageFolder
    Number of datapoints: 3360
    Root location: D:/COVID_COUGH_SOUNDS/50S_overlap_458/50ms_stft_images/train
    StandardTransform
Transform: Compose(
               Resize(size=[224, 224], interpolation=bilinear, max_size=None, antialias=None)
               ToTensor()
               Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
           )

In [56]:
len(train_dataset)

3360

In [66]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_dataset, batch_size=1, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=1, shuffle=True)
#valid_dataloader = DataLoader(valid_dataset, batch_size=96, shuffle=True)

In [49]:
import torch 
import torch.nn as nn
import torchvision.models as models
#resnet18 = models.resnet18(pretrained=True)
alexnet = models.alexnet(pretrained=True)
vgg16 = models.vgg16(pretrained=True)
#squeezenet = models.squeezenet1_0(pretrained=True)
densenet = models.densenet161(pretrained=True)
#inception = models.inception_v3()

In [50]:
densenet

DenseNet(
  (features): Sequential(
    (conv0): Conv2d(3, 96, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (norm0): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu0): ReLU(inplace=True)
    (pool0): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (denseblock1): _DenseBlock(
      (denselayer1): _DenseLayer(
        (norm1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(96, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(192, 48, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer2): _DenseLayer(
        (norm1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (rel

In [51]:


for param in densenet.parameters():
    param.requires_grad = False
    
densenet.classifier = nn.Linear(2208,2)


In [52]:
densenet

DenseNet(
  (features): Sequential(
    (conv0): Conv2d(3, 96, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (norm0): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu0): ReLU(inplace=True)
    (pool0): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (denseblock1): _DenseBlock(
      (denselayer1): _DenseLayer(
        (norm1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(96, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(192, 48, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer2): _DenseLayer(
        (norm1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (rel

In [53]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [67]:
for i, data in enumerate(train_dataloader, 0):
            
            inputs, labels = data[0].to(device), data[1].to(device)
            print(labels)

tensor([4], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([3], device='cuda:0')
tensor([3], device='cuda:0')
tensor([2], device='cuda:0')
tensor([2], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([3], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([2], device='cuda:0')
tensor([3], device='cuda:0')
tensor([3], device='cuda:0')
tensor([4], device='cuda:0')
tensor([3], device='cuda:0')
tensor([4], device='cuda:0')
tensor([0], device='cuda:0')
tensor([3], device='cuda:0')
tensor([2], device='cuda:0')
tensor([3], device='cuda:0')
tensor([3], device='cuda:0')
tensor([3], device='cuda:0')
tensor([2], device='cuda:0')
tensor([2], device='cuda:0')
tensor([0], device='cuda:0')
tensor([3], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([2], device='cuda:0')
tensor([3], device='cuda:0')
tensor([3], device='cuda:0')
tensor([4], device='cuda:0')
tensor([3], de

KeyboardInterrupt: 

In [74]:
def train_model_and_test(model, learning_rate):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=0.9)
    model.to(device)
    print('Starting training with learning rate = '+ str(learning_rate))
    for epoch in range(5):
        running_loss = 0.0
        for i, data in enumerate(train_dataloader, 0):
            
            inputs, labels = data[0].to(device), data[1].to(device)
            if (labels==2)|(labels==0):
                optimizer.zero_grad()
                output = model(inputs)
                loss = criterion(output, labels)
                loss.backward()
                optimizer.step()
                running_loss += loss.item()
                if i % 50 == 49:
                    print('[%d, %5d] loss: %.3f' %(epoch + 1, i + 1, running_loss / 50))
                    running_loss = 0.0
            

    print('Finished Training the model')
            
            
    
    correct = 0
    total = 0
    with torch.no_grad():
        for data in test_dataloader:
            images, labels = data[0].to(device), data[1].to(device)
            if (labels==1)|(labels==0):
                
            
                
                outputs = model(images)
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()
            accr = (100 * correct / total)
            
        print('Accuracy of the model network: %d %%' % (accr))
        return accr


In [1]:
import torch.optim as optim
#train_model_and_test(densenet, 0.01)

In [13]:
## CNN

In [70]:
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(44944, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 5)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1) # flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

In [71]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [92]:
for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(train_dataloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data
        if (labels==4)|(labels==3):

        # zero the parameter gradients
            optimizer.zero_grad()

        # forward + backward + optimize
            outputs = net(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

        # print statistics
            running_loss += loss.item()
            if i % 2000 == 1999:    # print every 2000 mini-batches
                print('[%d, %5d] loss: %.3f' %
                      (epoch + 1, i + 1, running_loss / 2000))
                running_loss = 0.0

print('Finished Training')

[2,  2000] loss: 0.136
Finished Training


In [93]:
correct = 0
total = 0
# since we're not training, we don't need to calculate the gradients for our outputs
with torch.no_grad():
    for data in test_dataloader:
        
        images, labels = data
        if (labels==4)|(labels==3):
        # calculate outputs by running images through the network
            outputs = net(images)
        # the class with the highest energy is what we choose as prediction
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

print('Accuracy of the network on the test images: %d %%' % (
    100 * correct / total))

Accuracy of the network on the test images: 68 %
