In [1]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from torch import nn
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt
import numpy as np
import tensorboard
import torchvision
from torch.utils.tensorboard import SummaryWriter
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))
from sklearn.model_selection import KFold

Using cuda device


In [144]:
transform = transforms.Compose(
            [#transforms.ToPILImage(),
            transforms.Resize([224, 224]),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
            transforms.ToTensor()])

In [82]:
import os
test_classes = []
test_x = next(os.walk('D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/test/allergies/'))[2]
test_y = next(os.walk('D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/test/covid/'))[2]
for i in range(len(test_x)):
    test_classes.append(0)
for i in range(len(test_y)):
    test_classes.append(1)

In [83]:
test_image_path = []

root_dir = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/test/'
classname1 = 'allergies/'
classname2 = 'covid/'

for index in range(len(test_x)):
    test_image_path.append(os.path.join(root_dir, classname1, test_x[index]))
for index in range(len(test_y)):
    test_image_path.append(os.path.join(root_dir, classname2, test_y[index]))


In [26]:
train_classes = []
train_x = next(os.walk('D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/train/allergies/'))[2]
train_y = next(os.walk('D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/train/covid/'))[2]
for i in range(len(train_x)):
    train_classes.append(0)
for i in range(len(train_y)):
    train_classes.append(1)

In [27]:
train_image_path = []

root_dir = 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/train/'
classname1 = 'allergies/'
classname2 = 'covid/'

for index in range(len(train_x)):
    train_image_path.append(os.path.join(root_dir, classname1, train_x[index]))
for index in range(len(train_y)):
    train_image_path.append(os.path.join(root_dir, classname2, train_y[index]))

In [28]:
train_image_path[:4]

['D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/train/allergies/1601354644605_0.png',
 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/train/allergies/1601354644605_1.png',
 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/train/allergies/1601354644605_2.png',
 'D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/train/allergies/1601354644605_3.png']

In [48]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])
z.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [89]:
from PIL import Image
  
# open method used to open different extension image file
im = Image.open(r'D:\COVID_COUGH_SOUNDS\1second_chunks_458\stft_images_1sec_no_overlap\test\allergies\1591363379163_0.png').convert('RGB')
  
# This method will show image in any image viewer 
im.show() 

In [267]:
from torch.utils.data import Dataset, DataLoader
from skimage import io
from PIL import Image
from torchvision import transforms
class LandmarkDataset(Dataset):
    def __init__(self, image_paths, classes, transform=None):
        self.image_paths = image_paths
        self.transform = transform
        self.classes = classes
        
    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
            
        image_filepath = self.image_paths[idx]
        image = io.imread(image_filepath )  
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = image.transpose((2, 0, 1))
        
        label = self.classes[idx]
        #label = np.array([label])
        label = torch.tensor(label, dtype  = torch.long)
        #sample = {'image': image, 'label': label}
        
        if self.transform:
            image = self.transform(image)
       
        
        return image, label

In [268]:
transform = transforms.Compose(
            [#transforms.ToPILImage(),
            transforms.ToTensor()])

In [269]:
train_dataset = LandmarkDataset(train_image_path,train_classes, transform)
test_dataset = LandmarkDataset(test_image_path, test_classes, transform)

In [270]:
train_dataset = LandmarkDataset(train_image_path,train_classes)
test_dataset = LandmarkDataset(test_image_path, test_classes)

In [271]:
train_loader = DataLoader(
    train_dataset, batch_size=1, shuffle=True
)
test_loader = DataLoader(
    test_dataset, batch_size=1, shuffle=True
)

In [272]:
for data in test_loader:
    inputs, labels = data[0], data[1]
    print(labels)

tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tens

KeyboardInterrupt: 

In [251]:
train_dataset

In [252]:
train_loader

In [234]:
len(train_classes)

1224

In [235]:
len(test_classes)

312

In [16]:
# 5 class classification
#train_dataset = datasets.ImageFolder(root='D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/train', transform=transform)
#test_dataset  = datasets.ImageFolder(root='D:/COVID_COUGH_SOUNDS/1second_chunks_458/stft_images_1sec_no_overlap/test',  transform=transform)
#valid_dataset  = datasets.ImageFolder(root='D:/split_data_breast/val',  
                                     #transform=transform)

In [17]:
#from torch.utils.data import DataLoader

#train_dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True)
#test_dataloader = DataLoader(test_dataset, batch_size=4, shuffle=True)

In [18]:
#train_dataset.targets

In [19]:
train_dataset

In [20]:
test_dataset

In [21]:
len(train_dataset)

1224

In [22]:
len(test_dataset)

312

In [23]:
#from torch.utils.data import DataLoader

#train_dataloader = DataLoader(train_dataset, batch_size=1, shuffle=True)
#test_dataloader = DataLoader(test_dataset, batch_size=1, shuffle=True)
#valid_dataloader = DataLoader(valid_dataset, batch_size=96, shuffle=True)

In [17]:
import torch 
import torch.nn as nn
import torchvision.models as models
#resnet18 = models.resnet18(pretrained=True)
alexnet = models.alexnet(pretrained=True)
vgg16 = models.vgg16(pretrained=True)
#squeezenet = models.squeezenet1_0(pretrained=True)
densenet = models.densenet161(pretrained=True)
#inception = models.inception_v3()

In [265]:


for param in densenet.parameters():
    param.requires_grad = False
    
densenet.classifier = nn.Linear(2208,2)


In [257]:
import cv2

In [258]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [259]:
len(train_classes)

1224

In [260]:
sample = next(iter(test_dataset))

In [261]:
sample

(array([[[255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255]],
 
        [[255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255]],
 
        [[255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255]]], dtype=uint8),
 tensor([0]))

In [262]:
#for i, data in enumerate(train_loader, 0):
            
            #inputs, labels = data[0].to(device), data[1].to(device)
            #print(labels)

In [273]:
def train_model_and_test(model, learning_rate):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=0.9)
    model.to(device)
    
    print('Starting training with learning rate = '+ str(learning_rate))
    for epoch in range(5):
        running_loss = 0.0
        for i, data in enumerate(train_loader, 0):
            inputs, labels = data[0].to(device), data[1].to(device)
            inputs = inputs.float()
            optimizer.zero_grad()
            output = model(inputs)
            loss = criterion(output, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
            if i % 50 == 49:
                print('[%d, %5d] loss: %.3f' %(epoch + 1, i + 1, running_loss / 50))
                running_loss = 0.0
            

    print('Finished Training the model')
            
            
    
    correct = 0
    total = 0
    #model(inputs.permute(0, 3, 1, 2))
    with torch.no_grad():
        
        for data in test_loader:
            images, labels = data[0].to(device), data[1].to(device) 
            images = images.float()
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
        accr = (100 * correct / total)
            
        print('Accuracy of the model network: %d %%' % (accr))
        return accr


In [274]:
import torch.optim as optim
train_model_and_test(densenet, 0.01)

Starting training with learning rate = 0.01
[1,    50] loss: 10.631
[1,   100] loss: 10.711
[1,   150] loss: 4.086
[1,   200] loss: 6.413
[1,   250] loss: 6.353
[1,   300] loss: 11.117
[1,   350] loss: 12.837
[1,   400] loss: 9.169
[1,   450] loss: 8.691
[1,   500] loss: 9.556
[1,   550] loss: 9.172
[1,   600] loss: 14.380
[1,   650] loss: 8.242
[1,   700] loss: 7.042
[1,   750] loss: 3.608
[1,   800] loss: 12.151
[1,   850] loss: 9.147
[1,   900] loss: 3.614
[1,   950] loss: 3.812
[1,  1000] loss: 21.160
[1,  1050] loss: 32.411
[1,  1100] loss: 13.885
[1,  1150] loss: 5.316
[1,  1200] loss: 5.218
[2,    50] loss: 7.223
[2,   100] loss: 9.656
[2,   150] loss: 8.551
[2,   200] loss: 9.845
[2,   250] loss: 12.550
[2,   300] loss: 7.500
[2,   350] loss: 5.452
[2,   400] loss: 8.534
[2,   450] loss: 3.598
[2,   500] loss: 8.823
[2,   550] loss: 4.528
[2,   600] loss: 4.414
[2,   650] loss: 11.358
[2,   700] loss: 5.407
[2,   750] loss: 9.885
[2,   800] loss: 6.691
[2,   850] loss: 7.441
[2

33.333333333333336

In [20]:
## CNN

In [35]:
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(44944, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 2)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1) # flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

In [36]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [55]:
for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(train_dataloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data
        if (labels==1)|(labels==0):

        # zero the parameter gradients
            optimizer.zero_grad()

        # forward + backward + optimize
            outputs = net(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

        # print statistics
            running_loss += loss.item()
            if i % 2000 == 1999:    # print every 2000 mini-batches
                print('[%d, %5d] loss: %.3f' %
                      (epoch + 1, i + 1, running_loss / 2000))
                running_loss = 0.0

print('Finished Training')

Finished Training


In [56]:
correct = 0
total = 0
# since we're not training, we don't need to calculate the gradients for our outputs
with torch.no_grad():
    for data in test_dataloader:
        
        images, labels = data
        if (labels==1)|(labels==0):
        # calculate outputs by running images through the network
            outputs = net(images)
        # the class with the highest energy is what we choose as prediction
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

print('Accuracy of the network on the test images: %d %%' % (
    100 * correct / total))

Accuracy of the network on the test images: 53 %
